
FROM python:3.12-slim

WORKDIR /usr/src/services

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./services .

CMD ["fastapi", "run","--host","0.0.0.0","--port","8000"]