version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    deploy:
      replicas: 1

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    deploy:
      replicas: 1

  backend:
    image: myapp-backend:latest
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      ASYNC_SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      MONGO_URL: mongodb://mongo:mongo@mongodb:27017/mydb?authSource=admin
      JWT_SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: 
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  celery_worker:
    image: myapp-backend:latest
    command: celery -A service.celery_config.celery_conf worker --loglevel=info
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      ASYNC_SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      MONGO_URL: mongodb://mongo:mongo@mongodb:27017/mydb?authSource=admin
      JWT_SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: stop-first

  celery_beat:
    image: myapp-backend:latest
    command: celery -A service.celery_config.celery_conf beat --loglevel=info
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      ASYNC_SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      MONGO_URL: mongodb://mongo:mongo@mongodb:27017/mydb?authSource=admin
      JWT_SECRET_KEY: z_f%#7x&0!n6uuamyca%y5swv1(9e=u=wu9s#wy(3f-k__k777
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres-data:
  mongo-data:
  smtp4dev-data: